smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -243,10 +243,10 @@ jobs:
                   name: Run migrations
                   command: |
                       cd backend
-                      cat .env
+                    #   cat .env
                       npm i
-                      npm run build
-                      npm run migrations
+                    #   npm run build
+                      npm run migrations > migrations_dump.txt
             - run:
                   name: Send migration results to KVDB.io
                   command: |
@@ -338,6 +338,49 @@ jobs:
             # Here's where you will add some code to rollback on failure
             - destroy-environment:
                   workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+    smoke-test:
+        docker:
+            # Lightweight Docker image
+            - image: python:3.7-alpine3.11
+        steps:
+            # Checkout code from git
+            - checkout
+            - attach_workspace:
+                  at: /root
+            - run:
+                  name: Install dependencies
+                  command: |
+                      apk add --update curl
+                      pip install awscli
+            - run:
+                  name: Backend smoke test.
+                  command: |
+                      BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                      --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                      --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                      --output text)
+                      export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+                      if curl -s $API_URL/api/status | grep "ok"
+                      then
+                      exit 0
+                      else
+                      exit 1
+                      fi
+            - run:
+                  name: Frontend smoke test.
+                  command: |
+                      URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+                      if curl -s ${URL} | grep "Welcome"
+                      then
+                        return 0
+                      else
+                        return 1
+                      fi
+            # Here's where you will add some code to rollback on failure
+            - destroy-environment:
+                  workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+            - revert-migrations:
+                  workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
 workflows:
     default:
@@ -368,3 +411,5 @@ workflows:
             - deploy-frontend:
                   requires:
                       - run-migrations
+            - smoke-test:
+                  requires: [deploy-backend, deploy-frontend]
